"""Adversary strategy implementations for SentinelX."""
from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Any, Dict, List


@dataclass
class Scenario:
    """A fully-specified fraud episode generated by a strategy."""

    fraud_type: str
    transaction: Dict[str, Any]
    user_profile: Dict[str, Any]

    # Hidden evidence — only revealed when agent queries
    velocity_data: Dict[str, Any] = field(default_factory=dict)
    device_history: Dict[str, Any] = field(default_factory=dict)
    ip_reputation: Dict[str, Any] = field(default_factory=dict)
    network_connections: List[Dict[str, Any]] = field(default_factory=list)
    behavioral_biometrics: Dict[str, Any] = field(default_factory=dict)
    active_sessions: List[Dict[str, Any]] = field(default_factory=list)
    temporal_pattern: Dict[str, Any] = field(default_factory=dict)
    business_registration: Dict[str, Any] = field(default_factory=dict)
    network_graph: Dict[str, Any] = field(default_factory=dict)

    # Ground truth
    is_fraud: bool = True
    structuring_detected: bool = False
    total_laundered_amount: float = 0.0


# ---------------------------------------------------------------------------
# Base strategy
# ---------------------------------------------------------------------------

class FraudStrategy:
    name: str = "base"

    def generate(self, task_id: str, seed: int, user_profile: Dict[str, Any]) -> Scenario:
        raise NotImplementedError


# ---------------------------------------------------------------------------
# Task 1: Stolen Card strategies
# ---------------------------------------------------------------------------

class HighVelocityStrategy(FraudStrategy):
    """Obvious stolen card — high velocity, location anomaly, new device, VPN."""

    name = "high_velocity"

    def generate(self, task_id: str, seed: int, user_profile: Dict[str, Any]) -> Scenario:
        rng = random.Random(seed)
        amounts = [rng.uniform(400, 2499) for _ in range(5)]

        txn_amount = round(rng.uniform(2000, 2499), 2)

        return Scenario(
            fraud_type="stolen_card",
            transaction={
                "transaction_id": f"TXN{seed:06d}",
                "amount": txn_amount,
                "merchant": "ElectronicsStore_3947",
                "location": "Miami, FL",
                "timestamp": "2024-04-02T03:47:00Z",
                "currency": "USD",
            },
            user_profile={
                "user_id": user_profile["user_id"],
                "account_age_days": user_profile["account_age_days"],
                "typical_location": user_profile["typical_location"],
                "typical_transaction_size": user_profile["typical_transaction_size"],
                "card_present_ratio": user_profile["card_present_ratio"],
            },
            velocity_data={
                "past_7_days_count": rng.randint(18, 35),
                "past_24_hours_count": rng.randint(8, 15),
                "past_1_hour_count": rng.randint(4, 7),
                "amounts": amounts,
                "locations": ["Miami, FL", "Orlando, FL", "Tampa, FL"],
                "typical_7_day_count": 3,
                "anomaly_score": 0.92,
            },
            device_history={
                "current_device": "New iPhone (never seen before)",
                "current_device_fingerprint": f"DEV{seed:08x}",
                "known_devices": [
                    {"device": user_profile.get("primary_device", "iPhone"), "last_seen": "2024-04-01T22:15:00Z", "trusted": True}
                ],
                "is_new_device": True,
                "device_risk_score": 0.88,
            },
            ip_reputation={
                "ip": "104.28.42.17",
                "type": "vpn_exit_node",
                "provider": "Cloudflare",
                "risk_score": 0.85,
                "country": "US",
                "is_hosting": True,
                "is_proxy": True,
                "is_vpn": True,
                "is_tor": False,
            },
            active_sessions=[
                {"device": "New iPhone", "location": "Miami, FL", "started": "2024-04-02T03:30:00Z", "current": True},
            ],
            is_fraud=True,
        )


class DeviceSpoofingStrategy(FraudStrategy):
    """Fraudster uses device emulator after being caught on velocity checks."""

    name = "device_spoofing"

    def generate(self, task_id: str, seed: int, user_profile: Dict[str, Any]) -> Scenario:
        rng = random.Random(seed)
        # Spaced-out transactions to defeat velocity
        txn_amount = round(rng.uniform(1500, 2499), 2)

        return Scenario(
            fraud_type="stolen_card",
            transaction={
                "transaction_id": f"TXN{seed:06d}",
                "amount": txn_amount,
                "merchant": "ElectronicsStore_3947",
                "location": user_profile["typical_location"],  # Faked location
                "timestamp": "2024-04-02T14:10:00Z",
                "currency": "USD",
            },
            user_profile={
                "user_id": user_profile["user_id"],
                "account_age_days": user_profile["account_age_days"],
                "typical_location": user_profile["typical_location"],
                "typical_transaction_size": user_profile["typical_transaction_size"],
                "card_present_ratio": user_profile["card_present_ratio"],
            },
            velocity_data={
                "past_7_days_count": 4,
                "past_24_hours_count": 2,
                "past_1_hour_count": 1,
                "amounts": [round(rng.uniform(100, 500), 2) for _ in range(4)],
                "locations": [user_profile["typical_location"]],
                "typical_7_day_count": 3,
                "anomaly_score": 0.22,  # Low — fraudster spaced out
            },
            device_history={
                "current_device": f"Emulated {user_profile.get('primary_device', 'iPhone')} (spoofed)",
                "current_device_fingerprint": f"EMU{seed:08x}",
                "known_devices": [
                    {"device": user_profile.get("primary_device", "iPhone"), "last_seen": "2024-04-01T20:00:00Z", "trusted": True}
                ],
                "is_new_device": True,
                "canvas_fingerprint_mismatch": True,
                "webgl_fingerprint_mismatch": True,
                "device_risk_score": 0.91,
            },
            ip_reputation={
                "ip": "45.33.32.156",
                "type": "datacenter",
                "provider": "Linode",
                "risk_score": 0.70,
                "country": "US",
                "is_hosting": True,
                "is_proxy": False,
                "is_vpn": False,
                "is_tor": False,
            },
            is_fraud=True,
        )


# ---------------------------------------------------------------------------
# Task 2: Account Takeover strategies
# ---------------------------------------------------------------------------

class BehavioralMimicryStrategy(FraudStrategy):
    """ATO — normal-looking transaction but behavioral signals betray the impostor."""

    name = "behavioral_mimicry"

    def generate(self, task_id: str, seed: int, user_profile: Dict[str, Any]) -> Scenario:
        rng = random.Random(seed)

        return Scenario(
            fraud_type="account_takeover",
            transaction={
                "transaction_id": f"TXN{seed:06d}",
                "amount": round(rng.uniform(100, 200), 2),
                "merchant": "DigitalGiftCards_Unlimited",
                "location": user_profile["typical_location"],  # Matches!
                "timestamp": "2024-04-02T14:22:00Z",
                "currency": "USD",
            },
            user_profile={
                "user_id": user_profile["user_id"],
                "account_age_days": user_profile["account_age_days"],
                "typical_location": user_profile["typical_location"],
                "typical_transaction_size": user_profile["typical_transaction_size"],
                "card_present_ratio": user_profile["card_present_ratio"],
            },
            behavioral_biometrics={
                "typing_wpm": rng.randint(130, 160),
                "user_baseline_wpm": user_profile["typing_wpm_baseline"],
                "mouse_pattern": "linear_robotic",
                "user_baseline_mouse": "human_curved",
                "session_duration_seconds": rng.randint(40, 60),
                "user_baseline_session_seconds": user_profile["average_session_minutes"] * 60,
                "keystroke_dynamics_score": 0.08,  # 0=robot, 1=human
                "anomaly_score": 0.94,
            },
            active_sessions=[
                {
                    "device": user_profile.get("primary_device", "iPhone"),
                    "browser": user_profile.get("primary_browser", "Safari"),
                    "location": user_profile["typical_location"],
                    "started": "2024-04-02T12:10:00Z",
                    "is_current": False,
                    "is_legitimate": True,
                },
                {
                    "device": "Android Chrome",
                    "browser": "Chrome on Android",
                    "location": user_profile["typical_location"],
                    "started": "2024-04-02T14:07:00Z",
                    "is_current": True,
                    "is_legitimate": False,
                },
            ],
            device_history={
                "current_device": "Android Chrome on Samsung Galaxy",
                "current_device_fingerprint": f"ATK{seed:08x}",
                "known_devices": [
                    {"device": user_profile.get("primary_device", "iPhone"), "last_seen": "2024-04-02T12:10:00Z", "trusted": True}
                ],
                "is_new_device": True,
                "device_risk_score": 0.82,
            },
            ip_reputation={
                "ip": "185.220.101.47",
                "type": "tor_exit_node",
                "provider": "Tor Project",
                "risk_score": 0.98,
                "country": "DE",
                "is_hosting": True,
                "is_proxy": True,
                "is_vpn": False,
                "is_tor": True,
            },
            velocity_data={
                "past_7_days_count": 3,
                "past_24_hours_count": 1,
                "past_1_hour_count": 1,
                "typical_7_day_count": 4,
                "anomaly_score": 0.12,
            },
            is_fraud=True,
        )


# ---------------------------------------------------------------------------
# Task 3: Money Laundering strategies
# ---------------------------------------------------------------------------

class StructuredPaymentsStrategy(FraudStrategy):
    """Money laundering via structured payments — single transaction looks normal."""

    name = "structured_payments"

    def generate(self, task_id: str, seed: int, user_profile: Dict[str, Any]) -> Scenario:
        rng = random.Random(seed)
        txn_amount = round(rng.uniform(9100, 9900), 2)

        return Scenario(
            fraud_type="money_laundering",
            transaction={
                "transaction_id": f"TXN{seed:06d}",
                "amount": txn_amount,
                "merchant": "Consulting_LLC_Delaware",
                "location": user_profile["typical_location"],
                "timestamp": "2024-04-02T10:00:00Z",
                "currency": "USD",
            },
            user_profile={
                "user_id": user_profile["user_id"],
                "account_age_days": user_profile["account_age_days"],
                "typical_location": user_profile["typical_location"],
                "typical_transaction_size": user_profile["typical_transaction_size"],
                "card_present_ratio": user_profile["card_present_ratio"],
                "business_type": user_profile.get("business_type", "Unknown"),
            },
            velocity_data={
                "past_7_days_count": 3,
                "past_24_hours_count": 1,
                "past_1_hour_count": 1,
                "amounts": [round(rng.uniform(9000, 9999), 2) for _ in range(3)],
                "typical_7_day_count": 2,
                "anomaly_score": 0.35,
            },
            network_connections=[
                {"node_id": "Consulting_LLC_Delaware", "type": "shell_company", "relationship": "payee", "depth": 1},
                {"node_id": "BUSSOC0012", "type": "individual", "relationship": "co-funder", "depth": 1},
                {"node_id": "BUSSOC0043", "type": "individual", "relationship": "co-funder", "depth": 1},
            ],
            temporal_pattern={
                "coordinated_accounts": 47,
                "date_range": "2024-03-25 to 2024-04-02",
                "all_amounts_sub_10k": True,
                "structuring_probability": 0.97,
                "timing_coordination_score": 0.94,
                "total_network_amount": 456700.00,
            },
            business_registration={
                "entity": "Consulting_LLC_Delaware",
                "state": "Delaware",
                "registered": "2023-11-01",
                "employees_reported": 0,
                "annual_revenue_reported": 0,
                "has_website": False,
                "has_phone": False,
                "shell_company_probability": 0.96,
            },
            network_graph={
                "depth_1": {
                    "nodes": ["Consulting_LLC_Delaware", "BUSSOC0012", "BUSSOC0043"],
                    "edges": 3,
                },
                "depth_2": {
                    "nodes": ["Consulting_LLC_Delaware", "BUSSOC0012", "BUSSOC0043",
                              "Offshore_Holdings_BVI", "Cayman_Investments"],
                    "edges": 7,
                    "offshore_entities": ["Offshore_Holdings_BVI", "Cayman_Investments"],
                    "crypto_exchanges": ["CryptoExchange_FastTrade"],
                },
            },
            is_fraud=True,
            structuring_detected=True,
            total_laundered_amount=456700.00,
        )


class ShellNetworkStrategy(FraudStrategy):
    """Advanced: deeper shell layers, mules as intermediaries."""

    name = "shell_network"

    def generate(self, task_id: str, seed: int, user_profile: Dict[str, Any]) -> Scenario:
        # builds on StructuredPaymentsStrategy but adds extra hop
        base = StructuredPaymentsStrategy().generate(task_id, seed, user_profile)
        base.network_graph["depth_3"] = {
            "nodes": base.network_graph["depth_2"]["nodes"] + ["Mule_Account_01", "Mule_Account_02"],
            "edges": 11,
            "mule_accounts": ["Mule_Account_01", "Mule_Account_02"],
            "note": "Unwitting intermediaries used to obscure trail",
        }
        base.fraudster_strategy = "shell_network"
        return base


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

STRATEGY_REGISTRY: Dict[str, type] = {
    "high_velocity": HighVelocityStrategy,
    "device_spoofing": DeviceSpoofingStrategy,
    "behavioral_mimicry": BehavioralMimicryStrategy,
    "structured_payments": StructuredPaymentsStrategy,
    "shell_network": ShellNetworkStrategy,
}
